### ISSUE TITLE
Rebase fails if file in picked commit has both content and permissions change

### ISSUE THREAD

**Issue by akikoskinen** [libgit2/libgit2#3158]
There seems to be an issue in the rebase functionality somewhere. I have trouble pinpointing where the issue is exactly but I have managed to create a test case to reproduce it.

This issue needs an operating system where the filesystem has permissions. It seems to affect Linux. OSX seems **not** to be affected, I was told. Windows probably isn't relevant for this issue.

## How to reproduce

Get the test case that shows the issue: https://github.com/akikoskinen/libgitrebasebug

Run the `createrepo.sh` script which creates a git repository that is used for the demonstration. This script can be run again and again in order to recreate the test repository - it removes any previous repository first.

In [`CMakeLists.txt` on line 5](https://github.com/akikoskinen/libgitrebasebug/blob/master/CMakeLists.txt#L5) modify the path to libgit2 code.

In [`main.c` line 6](https://github.com/akikoskinen/libgitrebasebug/blob/master/main.c#L6) you can specify whether using libgit2 0.22 branch or master branch. Both branches seem to be affected.

Build the test case and run it (see below). It terminates into an assert but it shouldn't.

    mkdir build && cd build && cmake .. && make && ./libgitrebasebug

## What's going on?

Look at the test repository (right after it's created, before running the test program). There's a `master` branch and a branch called `other`. Master branch is currently checked out.

One file is modified in the commit on the top of the master branch: `problem.txt`. There are two different kind of changes in that file: its contents and its file permissions have been changed.

On the `other` branch the `problem.txt` file is not modified at all.

Rebasing `master` on top of `other` should succeed just fine. Indeed `git rebase other` does that just fine.

The test program tries to do exactly what `git rebase other` does but it fails to do that.

## Other info

The problem seems to occur only when both the contents and the file permissions of the `problem.txt` file are changed. If only one or the other kind of change is present then the rebase succeeds.

**Comment by karvaporo** [comment]
I think I have managed to track down this issue. At ```git_rebase_init``` there is a call to ```git_reference_create``` and ```git_checkout_head``` which is supposed to set the head to the tip of the onto-branch and update the index and workdir correspondingly. However, ```git_checkout_head``` does not update the permissions of the file ```problem.txt``` in this scenario but leaves them to ```0100755```. Thus ```git_rebase_init``` leaves the repository in a state where uncommitted changes exist and the subsequent call to ```git_rebase_next``` fails.

The permissions should probably be explicitly set somewhere in ```checkout_blob``` or somewhere deeper into the call chain.

If the config variable ```core.ignorecase``` is set to true (which seems to be the case in OS X), then ```problem.txt``` is deleted in ```mkpath2file``` prior to checkout, so the file permissions will be set correctly.

**Comment by carlosmn** [comment]
If the bug is due to failing to apply filemode changes on checkout, that should be fixed in master already. You can try grabbing the updates from #3138 which brings in a fix for this issue.

**Comment by akikoskinen** [comment]
I tried with the current master (currently at be5fda75879f7ed89c7a72adc257872d1ea13803) but the issue still remains.

**Comment by karvaporo** [comment]
I have made a test case to reproduce the issue in 4950ebb210672d379af74e856e6f3cff772b422f, which the current master fails. What precisely goes wrong is this: If v1 of file A exists in current work directory and there is a commit in the repo that has v2 of A, which differs from v1 by file mode, then checking out the tree in the commit will copy the v2 into the work dir but will retain the file mode of v1 unless v2 is executable. I've made a proposed fix in 023c1ad791bf7528d93f9e1d11eba4a715d2d16e.
