### ISSUE TITLE
How can I check if my libgit2 has been compiled with libssh2 support?

### ISSUE THREAD

**Issue by ccrivelli** [libgit2/libgit2#3605]
I'm compiling libgit2 to use it with pygit2 and salt-master.
My steps are the follwing ones:
```

# tar zxvf v0.23.4.tar.gz 
# cd libgit2-0.23.4/

# cmake .
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- checking for module 'libcurl'
--   found libcurl, version 7.29.0
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
-- Found HTTP_Parser: /usr/include  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- checking for module 'libssh2'
--   found libssh2, version 1.4.3
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Failed
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED - Success
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED - Failed
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED - Success
-- Looking for futimens
-- Looking for futimens - found
-- Looking for qsort_r
-- Looking for qsort_r - found
-- Looking for qsort_s
-- Looking for qsort_s - not found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Found PythonInterp: /bin/python (found version "2.7.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/libgit2-0.23.4


# make
# make install
[ 22%] Built target git2
[100%] Built target libgit2_clar
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/libgit2.so.0.23.4
-- Installing: /usr/local/lib/libgit2.so.23
-- Installing: /usr/local/lib/libgit2.so
-- Installing: /usr/local/lib/pkgconfig/libgit2.pc
-- Installing: /usr/local/include/git2
.. etc..


# pip uninstall pygit2
# export LDFLAGS="-Wl,-rpath='/usr/local/lib',--enable-new-dtags $LDFLAGS"
# pip install pygit2 --upgrade

(check versions)
# python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2
>>> pygit2.__version__
'0.23.3'
>>> pygit2.LIBGIT2_VERSION
'0.23.4'



(then I test to sync the local repo using gitfs)
# salt-run fileserver.update
[ERROR   ] Unable to fetch SSH-based gitfs remote 'git@github.com/myrepo.git'. libgit2 must be compiled with libssh2 to support SSH authentication.
True

```

As I still don't understand if it could be a libgit2 issue or a pygit2 issue or a salt-master one,
how can I be sure that libgit2 has been compiled with libssh2 support?

In my cmake step I see:

```
-- checking for module 'libssh2'
--   found libssh2, version 1.4.3
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found

```

and libssh headers are already installed (it's a Centos7 box):

```
# rpm -qa | grep libssh2
libssh2-devel-1.4.3-10.el7.x86_64
libssh2-1.4.3-10.el7.x86_64

```

Thanks

**Comment by ethomson** [comment]
I think that the relevant line here is:
> `-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found`

That function is required for support and ssh support is not available without a version of libssh2 that supports that.  Thus, you need to upgrade to a newer libssh2 that includes that function - it was added three years ago, roughly, and I'm surprised that your distribution does not support that.  [Version 1.4.3 is over three years old now](http://www.libssh2.org/changes.html), so I suspect that if you upgrade you will have more success.

**Comment by shiftkey** [comment]
You'll need 1.6.0 at minimum, as per the [docs](http://www.libssh2.org/libssh2_userauth_publickey_frommemory.html)

**Comment by carlosmn** [comment]
This isn't about `libssh2_userauth_publickey_frommemory()`. The CMake log does show that libssh2 was found. So libgit2 did find it and would have linked to it. The function to check there is [`git_libgit2_features()`](https://libgit2.github.com/libgit2/#HEAD/group/libgit2/git_libgit2_features) which should return that it does support it.

It looks like your pygit2 module is linking against a different libgit2 `.so` than the one you show compiling. Have you double-checked that your `salt-run` is actually running against the libgit2 you just compiled? Have you tried performing a clone from a python shell?

**Comment by carlosmn** [comment]
`'git@github.com/myrepo.git'` is not a SSH URL, so it seems rather odd that it would get that far in.

**Comment by ccrivelli** [comment]
@carlosmn Thanks.
Yes, you're right about the SSH URL, I was just following the salt docs here: https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#ssh

and they say:

```
SSH repositories can be configured using the ssh:// protocol designation, or using scp-like syntax. So, the following two configurations are equivalent:

- ssh://git@github.com/user/repo.git
- git@github.com:user/repo.git
```
and It's still misleading to get an error like ``` ' libgit2 must be compiled with libssh2 to support SSH authentication' ``` if the url is worng.

Anyway I also tested the salt-master using the URL: 
```
- ssh://git@github.com/myrepo.git:
```

and I got the following error (hopefully the real error):
```
# salt-run fileserver.update
[ERROR   ] Error occured fetching gitfs remote 'ssh://git@github.com/myrepo.git': Failed to connect to github.com: Connection timed out
True
```

my salt-master config includes:
```
# cat /etc/salt/master.d/gitHub.conf 
# git backend fileserver
fileserver_backend:
  - git

# GitPython or pygit2
gitfs_provider: pygit2
gitfs_base: master

# ssh 
gitfs_remotes:
  - ssh://git@github.com/myrepo.git:
    - root: dir/subdir
    - mountpoint: salt://srv
    - pubkey: <mypublickey>
    - privkey: <myprivatekey>
    - passphrase: <mypasshprase>
```

A manual 'git clone' test works from bash:
```
# git clone ssh://git@github.com/myrepo.git
..
[It asks me for passphrase twice as it's jumping on a different host via ssh]
..
Receiving objects: 100% (18363/18363), 44.83 MiB | 12.21 MiB/s, done.
Resolving deltas: 100% (6540/6540), done.
```

The github.com "Host" is defined in my .ssh/config to pick up the correct the keys and jump on a different host, like:
```
Host github.com
  Hostname              github.com
  User                  git
  IdentityFile          "<myprivatekey>"
  IdentitiesOnly        yes
  ProxyCommand          ssh -i "<myprivatekey>" -W %h:%p user@jumphost 2> /dev/null
```

Now, following your advice, I'm trying to clone the repo using python shell.
I tried the following.

With the wrong url:
```
# python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygit2 import clone_repository
>>> url = 'git@github.com/myrepo.git'
>>> path = '/tmp/repo'
>>> repo = clone_repository(url, path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 255, in clone_repository
    check_error(err)
  File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Unsupported URL protocol
```
with the correct url:
```
>>> url = 'ssh://git@github.com/myrepo.git'
>>> repo = clone_repository(url, path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 255, in clone_repository
    check_error(err)
  File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Failed to connect to github.com: Connection timed out
```

getting the same 'Connection timed out' error of my salt-master.

At this stage, I think I should find out a way to configure the passphrase and private-key from the python shell before cloning the repo, as pygit2 is not reading from .ssh/config file.
Correct?

Thanks .

**Comment by carlosmn** [comment]
libgit2 does not use the ssh configuration. libssh2 does not provide a way to read it, and I don't know that we would be able to do anything sensible with it if we did.

**Comment by ccrivelli** [comment]
Ok, thanks @carlosmn 
It sounds like there is no way at the moment (correct me if I'm wrong) to sync a github repo with salt-master using pygit2 behind a proxy.

I also tested it with https (rather then ssh) - I guess It's still using libgit2 -  and It didn't work either, I opened this github issue on salt page for that: https://github.com/saltstack/salt/issues/30990

To further clarify my saltmaster is not directly exposed to internet, but behind a proxy/jumphost, like:

```
saltmaster --> proxy/jb --> github.com
```

I was able to perform a 'git clone' in the python shell from the proxy/jb host (the version of pygit2 and libgit2 is different though - installed from the Centos7 repo: ``` yum install python-pygit2 pkg ``` ):

```
>>> remote.fetch()
<pygit2.remote.TransferProgress object at 0x7f5783097390>
>>>
>>> clone_repository('ssh://git@github.com/myrepo.git', '/tmp/repo2', credentials=cred)
pygit2.Repository('/tmp/repo2/.git/')
>>> 
>>> 

---- version ---
>>> import pygit2
>>> pygit2.__version__
'0.21.4'
>>> pygit2.LIBGIT2_VERSION
'0.21.0'
>>> 
```
But I wasn't able to do it from the from saltmaster host yet.

**Comment by carlosmn** [comment]
We support HTTP proxies through curl (at least in master, I'm not sure if we've released with that yet), but to do stuff that the OpenSSH client does, you'd need to shell out to that. The simplest way right now is to use the git tool, since I don't think pygit2 supports custom transports.

**Comment by ccrivelli** [comment]
ok, thanks.
I was able to do it using **GitPython** as it sounds like it can read ```.ssh/config``` with the limitation of the ssh private key with no passphrase though.
My salt-master repo is now fetched from github, even if I still have to find out how to map it with my local env.

I close this issue.

Thanks for the support.

**Comment by ccrivelli** [comment]
But it sounds like salt is still not stable as I0m finding a lot of open issues (many for the **gitfs**). 
So your advice ```to use the git tool``` is maybe the best solution.

**Comment by h3** [comment]
Can't believe it's 2018 and I'm still fighting this issue.

Everything works well until you need a repo with authentication. Then you need to install libraries and compiling tools to build latest vesion of lbssh2 to find out it just does not work anyhow.

It is a major pain in the a**. Every. Single. Time.

**Comment by KeksBeskvitovich** [comment]
@h3 That's ok.. 2020, problem still here

**Comment by tek0011** [comment]
2024 still an issue.

**Comment by ethomson** [comment]
> 2024 still an issue

@tek0011 can you provide a little more clarity on *what the issue is*? Instead of a passive aggressive comment on a years-old closed issue, we could help you if you provided a constructive discussion thread in the forum. A lot has changed.
