### ISSUE TITLE
git_revwalk_next is slow on first iteration since v0.25

### ISSUE THREAD

**Issue by rgburke** [libgit2/libgit2#4428]
git_revwalk_next is slow on its first iteration for versions 0.25, 0.26 and master when compared to v0.24. This is especially noticeable on large repositories.

### Reproduction steps
Run the following program on the Linux kernel source tree (https://github.com/torvalds/linux):

```c
#include <stdio.h>
#include <git2.h>

int main(int argc, char *argv[]) {
        git_libgit2_init();

        git_repository *repo;
        if (git_repository_open(&repo, ".git")) {
                fprintf(stderr, "Failed to open repository\n");
                return 1;
        }

        git_oid oid;
        git_oid_fromstr(&oid, "a0651c7fa2c088a605f63792279859608ed7f2c8");

        git_revwalk *revwalk;
        git_revwalk_new(&revwalk, repo);
        git_revwalk_sorting(revwalk, GIT_SORT_TIME);
        git_revwalk_push(revwalk, &oid);

        if (!git_revwalk_next(&oid, revwalk)) {
                git_commit *commit;

                if (git_commit_lookup(&commit, repo, &oid)) {
                        fprintf(stderr, "Failed to lookup commit\n");
                        return 1;
                }

                printf("%s\n", git_commit_message(commit));
                git_commit_free(commit);
        }

        git_revwalk_free(revwalk);
        git_repository_free(repo);

        return 0;
}
```

### Expected behavior
When using v0.24 this program runs in a couple of milliseconds:
```
richard@DevNew:~/code/linux$ time ./revwalktest >/dev/null

real	0m0.006s
user	0m0.000s
sys	0m0.006s
```

### Actual behavior
When using v0.25, v0.26 or master this program has not completed after 1 minute:
```
richard@DevNew:~/code/linux$ timeout 60s ./revwalktest
richard@DevNew:~/code/linux$ echo $?
124
```

### Version of libgit2 (release number or SHA1)
v0.25, v0.26 & master

### Operating system(s) tested
```
Linux DevNew 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tiennou** [comment]
I've tried to reproduce this by borrowing and hacking our `rev-list` example, but I don't quite get the same results :

- [0.24.1](https://github.com/tiennou/libgit2/tree/perf/revwalk-0.24) : `./rev-list --git-dir=$linux-kernel --date-order  >   11,84s user 1,89s system 72% cpu 18,930 total`
- [master](https://github.com/tiennou/libgit2/tree/perf/revwalk-master) : `./rev-list --git-dir=$linux-kernel --date-order  >   26,72s user 0,74s system 99% cpu 27,493 total`

My linux-kernel master is at `178e834c47b0d01352c48730235aae69898fbc02` (722113 commits from your base 😮).

I'm clearly not seeing sub-ms runs on 0.24, though we seem do seem to be more than twice slower.

Just for kicks, git-2.15.1 : `\git rev-list a0651c7fa2c088a605f63792279859608ed7f2c8 > /dev/null  6,50s user 0,57s system 99% cpu 7,087 total`

**Comment by battlmonstr** [comment]
I've ran across the same issue with [libgit2sharp](https://github.com/libgit2/libgit2sharp) that uses libgit2 under the hood. It seems that at some point GIT_SORT_NONE and GIT_SORT_TIME became several orders of magnutude slower, but GIT_SORT_TOPOLOGICAL and GIT_SORT_REVERSE became about 2x faster.

In my tests it happens between versions:
LibGit2Sharp.NativeBinaries.1.0.163 (libgit2sharp 0.23)
LibGit2Sharp.NativeBinaries.1.0.129 (libgit2sharp 0.22)

I'm sorry that I don't know which versions of libgit2 it corresponds to.

@tiennou note that in your test when you do `git rev-list HEAD > /dev/null` that actually interates through all the revisions _from the beginning of the world creation_. Try `time git rev-list HEAD | head` instead. It takes just about 50 ms for me. In the example of @rgburke it doesn't read through all revisions, it just reads the first one. This is my problem as well, because in a typical UI setting I usually just want to look around the latest changes, which is done instantly with `git log -10 > /dev/null` or even quite fast with `git log -1000 > /dev/null`, but gets dramatically slower with  `git log > /dev/null`.

**Comment by neithernut** [comment]
Regarding the performance regression reported in multiple issues, I selected this one for further investigation since it has the simplest reproducer.

I think the performance regression is in `limit_lists()`. Apparently, the loop containing the call to `add_parents_to_list()` is run several thousand times for a small input list (`commits`), e.g. 4 items. I'll continue looking into this and provide updates.

**Comment by neithernut** [comment]
https://github.com/libgit2/libgit2/blob/b00a09b0665281a327d3e3eab39d6c4723ad74ec/src/revwalk.c#L416

Mh... if I read the source correctly, `limit_list()` will accumulate the entire history of all commits supplied to it (via `list`): each iteration will add all parents of the current commit if its not previously marked as "uninteresting". Uninteresting and hidden commits will be ignored, all others will be added to the output list. This would explain the regression reported in this issue, since the first call to `git_revwalk_next` looks at the entire history, which is somewhat unfortunate (but it doesn't necessarily explain the regressions reported in #4736 and #4740).

If I'm not mistaken, commits are  ignored _after_ the parents are added to the `list`. Hence, the entire history of a commit is visited regardless of whether any of them would end up in the output list. @carlosmn?

**Comment by neithernut** [comment]
After giving this some thought, I don't think that the _general_ problem can be solved realistically given the current revwalk interface and the semantics.

If the revwalk is configured to yield all ancestors of a commit since a given point in time, we have to consider the commit's full history. At least if we don't assume that a parent (or a subgroup of ancestors) always has a timestamp smaller than the commit's timestamp.

If we consider hidden commits, the hidden commit's full history has to be considered since all its parents are also hidden. For example, if there is a merge-base between a "pushed" and a "hidden" commit, the revwalk will yield commits up to but not including that merge-base. We clearly don't want to break that contract, since other code already relies on this behaviour.

If the revwalk is not configured with particular sorting or hidden commits, it will yield the full history anyway. In this case, however, we don't have to consider the full history in advance. E.g. we could use a shortcut in this case, making the first call of `git_revwalk_next()` faster.

Comments are welcome, especially ones pointing out flaws in my argumentation. I, too, would like a faster revwalk implementation.

----

A more reasonable alternative might be an additional interface offering something like a dumb revwalk. This dumb revwalk would:
 * provide functions for pushing commits,
 * would _not_ provide functions for "hiding" commits, at least with the same guarantees (alternatively, it may provide explicit "stop-points", e.g. oids which make the revwalk stop at that commit),
 * doesn't know anything about sorting.

Thins might be sufficient for some users who want fast iterations but don't need the guaranteed and conveniences provided by the current revwalk. Also, the real revwalk could be simplified using the dumb one.

**Comment by pks-t** [comment]
I don't think another API would be needed, as you can already achieve all the things you want the revwalk to perform. You can disable sorting, do not have to call `git_revwalk_hide` and (obviously) can already push commits. I'd rather say that we should improve/extend upon what we already have.

As you said, we cannot really stop labelling parents as "hidden" with our existing API, as otherwise the results would be plain wrong in many cases. But what about something like `git_revwalk_limit`, which you can call multiple times with an OID to set straight limits to the graph. So in the case of marking a commit as hidden, we'd just proceed marking its parents as hidden as long as we didn't hit any of the limiting OIDs yet, effectively culling the tree. While this is no general solution, it at least could help certain use cases when there is a known commit from where on everything else is clearly uninteresting. One scenario where it would be helpful is e.g. ahead/behind count, where you could use the merge base as a limiting commit, so that we won't process the rest of the tree.

It certainly is applicable to some scenarios, only, but as I'd think it to be rather easy to implement I think it would be a worthwhile addition. I don't know whether it would fix all the usecases that have stumbled upon this performance regression, though, so input is welcome.

**Comment by neithernut** [comment]
> I don't think another API would be needed, as you can already achieve all the things you want the revwalk to perform. You can disable sorting, do not have to call `git_revwalk_hide` and (obviously) can already push commits. I'd rather say that we should improve/extend upon what we already have.

Using the API that is there would clearly be beneficial. It would also provide existing users with benefits without the need for them to change their code. However, I feel that it is quite easy to run into an unmaintainable hell of uncountable special-cases where we would either choose a less complex behaviour or bail out of it, resorting to looking at the entire history again.

I guess we'll never know without trying. Maybe I'll find some time for looking into it again in the near future.

> As you said, we cannot really stop labelling parents as "hidden" with our existing API, as otherwise the results would be plain wrong in many cases. But what about something like `git_revwalk_limit`, which you can call multiple times with an OID to set straight limits to the graph.

Sounds good.

> One scenario where it would be helpful is e.g. ahead/behind count, where you could use the merge base as a limiting commit, so that we won't process the rest of the tree.

The question would be, in this case, how much determining the merge-base costs. After fiddeling around with the reproducer provided in #4740, it doesn't look too bad, though.

**Comment by neithernut** [comment]
Would it be acceptable to push the process of hiding commits into the `git_revwalk_hide()` family of functions? They _are_ meant to be configuring functions. However, this way the cost of performing the operation would be clearly associated with the action triggering it.

**Comment by carlosmn** [comment]
It looks like there's a couple of things to the original report.

First there's the regression, but there's also the thing about the first call being slow. That is going to be the case unless we expand the API as the first call to `_next()` is when we actually perform the walk. In the past we had some code to spread the cost over all the different calls, but as we've been changing the code it looks more and more like git's, which does do the iteration all at once when there are negative refs (hidden commits).

It probably makes sense to expand the API to prepare the walk explicitly, but this part isn't new. Certain sorting combinations have always had this behaviour in libgit2.

**Comment by pks-t** [comment]
@stofte: this issue should be fixed by now on master. The code you've linked to passes in less than a second on my local machine, so there does not seem to be an initial hit anymore.

**Comment by battlmonstr** [comment]
Which version is it going to be release in?

**Comment by battlmonstr** [comment]
I have tried v0.28.0 (bundled with libgit2sharp) and as far as I understand this is still not fixed in case if GIT_SORT_TIME is present (see a [comment here](https://github.com/libgit2/libgit2sharp/issues/1558#issuecomment-464381468) ).

In the discussion above @neithernut and @pks-t suggested an idea to introduce a new "pagination" API call like `git_revwalk_limit(git_revwalk *revwalk, unsigned int limit)` that would tell the log walker algorithm that we don't need the full log, and thus it can try to optimize the process.
This call was not implemented yet, wasn't it?

Suppose that we have this API, then it might be possible to optimize the `GIT_SORT_TIME` case (but maybe have a new option - `GIT_SORT_TIME_OPTIMISTIC`, see below).
The optimization heuristic I'd like to propose is this: 
The natural commit order (let's call it "storage" order) is not sorted in the git database structure, but it is "almost" sorted in the vast majority of cases. What I mean by that is that the further you go back in the storage order log, the less is the probability that you are going to see a commit that has a date that is close to the ones in the tip of the log. This is true if the time between commit and push tends to be relatively short. Although this is true for many "usual" repos, this might not be true for some artificially constructed repos, and some corner cases. Example of an odd case is if you commit something a month ago, but push it today, and you are lucky to get no conflicts (while there was an active development in the meantime). That's why to be 100% correct this strategy should be enabled by some new option like `GIT_SORT_TIME_OPTIMISTIC`, not to mess with the `GIT_SORT_TIME` "correct" behaviour.

Example: Let's imagine that we have a "usual" repo and set the limit to 15 by calling `git_revwalk_limit(15)`. While walking in the storage order we first get 15 commits. Then we need to walk a bit more, because maybe we have some odd commits among the first 15 that were committed too long ago, and need to be thrown away from the results. While walking further we estimate the "stability" of the list, meaning the number of items we have to throw away from the existing list of results. If the list is very stable and doesn't change as we continue, we are ready with the results.

I understand that this might be a bit too crazy idea to implement in the core library especially if the behaviour now matches with the vanilla git. If so, this could still be done by a client or an extension. It can wrap `git_revwalk_*`, and implement this `GIT_SORT_TIME_OPTIMISTIC` on top of `GIT_SORT_NONE`.

**Comment by battlmonstr** [comment]
Please disregard what I was saying about corner cases and pushing. I don't know enough about the order in which git stores commits. If the storage order is always incremental (e.g. if new each new commit is "appended" to existing log at the end) then this order should exactly match to the commit date order in all cases (like local commits, push, rebase, force push, single branch or merge commits).

Is this understanding correct or not? If not, what are the cases in which `GIT_SORT_NONE` order differs from `GIT_SORT_TIME` order?

The only example I have in mind is if one's clock is not synchronized with the world time, and then the commit time that comes from that end is plain wrong. This case could be covered if the walker went a few hours back in the log after it finds enough commits, supposing that normal users will not set their clock too different from the world time.

**Comment by neithernut** [comment]
You can reorder commits during a rebase, and the author-date of each commit is preserved. So you can quite easily produce a sequence of commits with arbitrary order of author-dates. AFAIK the author-date is irrelevant for sorting, but if you pass `--committer-date-is-author-date` to `rebase` the author-date of each commit will also be used as the committer date.

While reordering commits during a rebase is not uncommon, I doubt that many people are using said option during a rebase. But you never know...

**Comment by battlmonstr** [comment]
@neithernut Are you saying that `GIT_SORT_TIME` corresponds to author dates?

As I understand if you rebase, it creates new commits with new commit dates, so it should preserve the commit date ordering, i.e. storage order still matches the commit date order.

About system times - yes, they drift, but they shouldn't drift too much. The algorithm can walk say 24 hours back to compensate for this drift.

**Comment by neithernut** [comment]
No, I was implying that the committer-date was used for sorting. I was saying that the author-date is used as the committer date when doing a `rebase --committer-date-is-author-date`, which will yield a potentially "scambled" sequence of committer-dates.

Regarding system-times: In a sane setup, the drift should indeed not be too high. There were machines (e.g. Netras produced by Sun Microsystems, I beliefe) with particularly unstable RTCs, but even with them you wouldn't have a problem with a sane NTP-config.

However, I wouldn't be too surprised if some idiot would use a Raspberry Pi without an RTC and/or a proper NTP-config (and the default password) in production. Especially nowadays.

**Comment by ethomson** [comment]
> I have tried v0.28.0 (bundled with libgit2sharp) and as far as I understand this is still not fixed in case if GIT_SORT_TIME is present (see a [comment here](https://github.com/libgit2/libgit2sharp/issues/1558#issuecomment-464381468) ).

1. Can you define "slow"?  What's the command that you're running on the command line?  What's the corresponding libgit2 code?  What's the comparison in execution time?
2. Can you point us to a repository to reproduce?
3. Are you sure that this is slow in libgit2, or is it possible that LibGit2Sharp is doing something additional here?

**Comment by battlmonstr** [comment]
I'm pretty sure that this is about libgit2. Now when you asked I've managed to reproduce it with the plain libgit2.

I've created a C++ console app using the code of @rgburke form this issue (see "Reproduction steps" above). The only change was that I pointed it to a clone of [cpython repo](https://github.com/python/cpython) and an initial commit SHA - set to [38f11cc3f62db11a4a24354bd06273322ac91afa](https://github.com/python/cpython/commit/38f11cc3f62db11a4a24354bd06273322ac91afa). If you want I can share the code and the project files on GitHub. It requires libgit2-0.28.1, git2.lib and git2.dll to run (I've built it from the 0.28.1 release source using CMake + VS 2012).

What is slow: the performance of this code depends on the number of total repo commits. It varies, but for the cpython repo ranges from 1.5-3 sec for Release builds and 3-5 seconds or more for Debug builds.
What is fast and potentially achievable: if you change GIT_SORT_TIME to GIT_SORT_NONE. This makes the test code run almost instantly.

Further debugging: 
I'm not an expert on C++ profiling on Windows, but I tried to run the profiler in VS 2012. Unfortunately profiling with CPU sampling crashes and reboots my laptop. Profiling with "Instrumentation" works, but it doesn't show git2.dll calls and internal calls for some reason, it just shows the main function total time and doesn't go deeper inside the library. I haven't figured out how to fix that yet.

Nevertheless, I was able to debug and put a breakpoint inside the libary source. It is clear that all the time is spent inside git_revwalk_next -> prepare_walk -> limit_list confirming findings of @neithernut . Inside limit_list there's a [while loop that calls add_parents_to_list](https://github.com/libgit2/libgit2/blob/master/src/revwalk.c#L422) multiple times. I have set a breakpoint with "Hit count", and with this it has shown that the number of add_parents_to_list calls at the end was 103311 which corresponds to the number of commits in this repo (see screenshot).

![2019-02-18 20_59_37-test4428 debugging - microsoft visual studio administrator](https://user-images.githubusercontent.com/11477595/52974917-8edd0700-33c3-11e9-8bc9-c6a9a1e37356.png)

**Comment by ethomson** [comment]
> _What is fast and potentially achievable_: if you change GIT_SORT_TIME to GIT_SORT_NONE. This makes the test code run almost instantly.

Well, yeah, but that's pretty apples and oranges.  That's why I asked what the comparative application you were running on the command line is and how long _it_ took.

Running `rev-list --date-order -n 1 HEAD` takes 0.78 seconds; a time-sorted `git_revwalk` takes 1.11.

Running `git log --date-order --oneline` takes 1.17 seconds; a time-sorted `git_revwalk` takes 1.48.

So, yes, obviously we're slower here.  But you're not asking about the time difference between libgit2 and git, you're making the comparison between `TIME` sorting and `NONE` sorting.  So it's not clear to me that if you got a revwalk down to git speeds that you'd be happy.  Or am I misunderstanding?

You've mentioned some "not really sorted" mode of sorting that is best effort and fast.  These are two orthogonal problems, I think, so I'm trying to understand which you're asking about.

**Comment by battlmonstr** [comment]
Yes you are right. The first call to libgit2's `git_revwalk_next` has similar performance (ballpark) as `git log --date-order -n 1` (for me it is 1.3-1.7 sec, with SSD). What is very interesting to me is why does libgit2 (and apparently core git :thinking: ) have to walk the entire 100K+ commit history, then throw it away and take the first one which was right there from the beginning? 

Do you reuse the core git code for libgit2 git_revwalk_next? If so then maybe it's not an issue of libgit2, but an issue of core git, and so this question should be raised to them.

If you aim to have comparable performance with the core git, this issue could be closed, because it kinda works as "intended".

**Comment by ethomson** [comment]
> What is very interesting to me is why does libgit2 (and apparently core git 🤔 ) have to walk the entire 100K+ commit history, then throw it away and take the first one which was right there from the beginning?

But how do you propose to identify that the first one is correct without doing the sort?

**Comment by ethomson** [comment]
> Do you reuse the core git code for libgit2 git_revwalk_next? If so then maybe it's not an issue of libgit2, but an issue of core git, and so this question should be raised to them.

To answer your direct question: there's some code borrowed, or was.  I couldn't tell you how much or if any remains.  But certainly the _goal_ is important.  If you want time-sorting, we aim to be compatible with git's time-sorting.

(And yes, that does mean walking the commits and sorting them, even if to discover that the `HEAD` commit was the newest.)

**Comment by battlmonstr** [comment]
I believe that they are "almost" sorted already, was proposing to just load N requested commits + enough commits such that a commit from 24 hours ago appears (to compensate the clock drift). Then sort those and spit out the first N. Probably it is naive and there's something I don't understand.

My plan is to switch to GIT_SORT_NONE, and see if users need _TIME or not. If they do, I could implement the naive strategy on top of GIT_SORT_NONE and wait to see if somebody complains again :)

I agree that it's a good idea to be compatible with git here.

**Comment by hackhaslam** [comment]
I've found that the limiting factor in a GUI client is drawing a graph. Users can typically compensate for dates that are a little out of order, but if you want to draw a graph, you have to have commits sorted topologically (which incurs the same cost). Otherwise, you end up with parents above their children and it breaks the graph drawing algorithm.

**Comment by pks-t** [comment]
> I believe that they are "almost" sorted already, was proposing to just load N requested commits + enough commits such that a commit from 24 hours ago appears (to compensate the clock drift). Then sort those and spit out the first N. Probably it is naive and there's something I don't understand.

The thing is libgit2 cannot really handle this while at the same time being conformant with git.git. But if I am not mistaken, the application developer is already able to do this limiting himself by using `git_revwalk_hide`. If you only want to sort the most-recent `n` commits and sort those by time, then you can `git_revwalk_hide` the `n+1`st commit. libgit2 will then handle this and all its parents as uninteresting, which _should_ in fact abort iteration and make your sorting fast again. I didn't test that assumption, but I'd certainly call it a bug if it didn't.

Other than that, there is no way that the time-based sort can avoid iterating all commits. Even though it is unlikely and maybe even bogus, it's always possible that the first commit in the repo is in fact the newest one.

**Comment by pks-t** [comment]
> I've found that the limiting factor in a GUI client is drawing a graph. Users can typically compensate for dates that are a little out of order, but if you want to draw a graph, you have to have commits sorted topologically (which incurs the same cost). Otherwise, you end up with parents above their children and it breaks the graph drawing algorithm.

Yeah, agreed. And as far as I know, `GIT_SORT_TOPOLOGICAL` doesn't have the same shortcoming of first having to enumerate _all_ commits.

**Comment by ethomson** [comment]
This issue deviated a bit from the original report.  I think that we've resolved the original reports, at least as much as possible.  I'd welcome work to continue to optimize revwalk.  I'm still very hesitant about a "best effort" mode, and I don't think that any of the core contributors are going to work on this.
