### ISSUE TITLE
Backslash escaped .gitignore glob patterns are not working

### ISSUE THREAD

**Issue by segevfiner** [libgit2/libgit2#5211]
### Reproduction steps
Run the following pygit2 script:
```py
#!/usr/bin/env python3
import sys
import pygit2


def main():
    repo = pygit2.init_repository("repo")
    open("repo/foo[123].txt", "w").close()
    with open("repo/.gitignore", "w") as f:
        f.write("foo\\[123].txt\n")

    print(repo.status())


if __name__ == "__main__":
    sys.exit(main())
```

### Expected behavior
`foo[123].txt` should be ignored. It is ignored by the git CLI.

### Actual behavior
It is untracked (`GIT_STATUS_WT_NEW`) by libgit2.

### Version of libgit2 (release number or SHA1)
0.28.2

### Operating system(s) tested
macOS 10.14.6

**Comment by buddyspike** [comment]
I think 10ac298c62 should fix this issue.

**Comment by pks-t** [comment]
Thanks @buddyspike, you're probably correct. I'll close this issue as it's fixed in master already, but please feel free to reopen if I'm mistaken about that. Anyway, thanks for your report!

**Comment by segevfiner** [comment]
Tried with libgit2 v0.28.4 and it is still not working. @pks-t

**Comment by ethomson** [comment]
@segevfiner v0.28.4 wouldn't have that fix in it.  v0.99 would.

**Comment by segevfiner** [comment]
Alright, I'll have to try that version. Might have to compile myself has Homebrew hasn't picked it up yet.
